### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by Monox18** [Ferruslogic/PhotonJSON#5]
The uniDecode and uniEncode functions were deprecated in LC 7.0 around 2014. I suggest replacing them with the equivalent textEncode and textDecode. Only a suggestion, thanks!

https://github.com/Ferruslogic/PhotonJSON/blob/3751420e316e4cef829276ddb90e5f0a2e216487/PhotonJSON.livecodescript#L565-L580

**Comment by torocruzand** [comment]
Thanks [@Monox18](https://github.com/Monox18), those functions have already been changed to their textDecode or textEncode equivalent. That made me think that you also don't have to do a check to see if the text is UTF-8. Since in the help it is specified that this library receives and returns a UTF-8 string.

**Comment by Monox18** [comment]
Thanks! Yah it makes sense to keep it UTF-8 on the developer side. I have also tested on my application and replaced fastJSON with this improved PhotonJSON which I believe is more future proof now.
